# Generated by Django 3.0.2 on 2020-01-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('categories', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('colours', models.CharField(max_length=150)),
                ('sizes', models.CharField(max_length=150)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
